version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:5487:5432
    environment:
      POSTGRES_USER: vehicleadmin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: vehicles
    volumes:
      - ./volumes/database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=dracula
    ports:
      - 127.0.0.1:9998:8080
